version: '3'
services:
  iris:
    build: 
      context: .
      dockerfile: "Dockerfile-iris"
    ports:
      - "52774:52773"
    hostname: iris
    command: "-p /data/pwd.txt"
    volumes:
       - ./conf:/data:ro
       - ./source:/source
  webgateway:
    build:  
      context: .
      dockerfile: "Dockerfile-webgateway"
      args:
        - LIB_PATH=./lib/WebGateway/bin
    ports: 
      - "8080:80"
